version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - "./prisma/migrations/20221128205402_init/migration.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: backend_container
    build:
      context: .
      target: builder
    environment:
      - UDP_PORT=5555
      - UDP_HOST=0.0.0.0
      - DATABASE_URL=postgresql://prisma:prisma@postgres/prisma?connection_limit=5&pool_timeout=0
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5555:5555/udp
      - 9229:9229 # debug port
    command: npm run start:docker

  clients:
    container_name: python_container
    build:
      context: ../python-producer
    depends_on:
      - backend
    ports:
      - 5556:5556/udp
    command: python3 clients.py backend 5555 3000

volumes:
  postgres:
